sudo: required

env:
  matrix:
    - DOCKER_IMAGE=ubuntu:18.04

services:
  - docker

language: c++

compiler:
  - gcc

before_install:
  - echo $DOCKER_IMAGE
  - docker pull $DOCKER_IMAGE
  - docker run -d -v $(pwd):/code $DOCKER_IMAGE /bin/bash -c 'while true; do sleep 1; done'
  - docker exec $(docker ps -aq) /bin/bash -c 'id'

before_script:
  - docker exec $(docker ps -aq) /bin/bash -c 'apt-get -qq update'
  - docker exec $(docker ps -aq) /bin/bash -c 'apt-get install -y --force-yes build-essential'

script:
  - docker exec $(docker ps -aq) /bin/bash -c 'cd /code && ls -a && ./.travis/build'
