sudo: required

env:
  matrix:
    - DOCKER_IMAGE=ubuntu:20.04 IGNITION_VERSION="citadel" ROS_DISTRO="noetic"
    - DOCKER_IMAGE=ubuntu:20.04 IGNITION_VERSION="dome" ROS_DISTRO="noetic"
    - DOCKER_IMAGE=ubuntu:20.04 IGNITION_VERSION="edifice" ROS_DISTRO="noetic"

services:
  - docker

language: c++

compiler:
  - gcc

before_install:
  - echo $DOCKER_IMAGE
  - echo $IGNITION_VERSION
  - docker pull $DOCKER_IMAGE
  - docker run -e IGNITION_VERSION -e ROS_DISTRO -d -v $(pwd):/code $DOCKER_IMAGE /bin/bash -c 'while true; do sleep 1; done'
  - docker exec $(docker ps -aq) /bin/bash -c 'id'

before_script:
  - docker exec $(docker ps -aq) /bin/bash -c 'apt-get -qq update'
  - docker exec $(docker ps -aq) /bin/bash -c 'apt-get install -y --force-yes build-essential'

script:
  - docker exec $(docker ps -aq) /bin/bash -c 'cd /code && ls -a && ./.travis/build'
